import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import EventSource from 'eventsource';

interface Data {
  status: string
  statusCode: number
  action: string
  body: Body
  requestTime: string
  responseTime: string
  processTime: string
}

interface Body {
  username: string
  currency: string
  whiteLabelName: string
  secureLogin: string
  hash: number
}

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [response, setResponse] = useState<Data>({
      status: '',
      statusCode: 0,
      action: '',
      body: {
        username: '',
        currency: '',
        whiteLabelName: '',
        secureLogin: '',
        hash: 0
      },
      requestTime: '',
      responseTime: '',
      processTime: '',
  });

  useEffect(() => {
    const url = 'http://10.25.155.177:8080/subs/openSinks/try';

    var es = new EventSource(url);

    const parseResponse:any = (msg: MessageEvent) => {
      console.log(msg.data)
      const parsed = JSON.parse(msg.data);
      console.log(parsed)
      setResponse(parsed);
    }

    es.addEventListener('message', parseResponse)

  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div>
          <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Status
            </h2>
            <p className={inter.className}>
              {response.status}
            </p>
          </a>

          <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Action
            </h2>
            <p className={inter.className}>
              {response.action}
            </p>
          </a>

          <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Response Time
            </h2>
            <p className={inter.className}>
              {response.responseTime}
            </p>
          </a>

          <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Process Time
            </h2>
            <p className={inter.className}>
              {response.processTime}
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
